{
 "title": "BlackboxExporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Site",
    "query": "label_values(probe_success, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Targets",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(sum(probe_success{instance=~\"$instance\"}) / count(probe_success{instance=~\"$instance\"})) * 100"
    }
   ]
  },
  {
   "title": "Certificate Expiry",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$instance\"} - time()",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Site Availability over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Response Times (seconds) over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "duration (seconds)" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS lookup time (seconds)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "probe_dns_lookup_time_seconds{instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "HTTP time (seconds)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ phase }}"
      },
      {
       "expr": "sum(probe_http_duration_seconds{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{ instance }} - total"
      }
     ]
    },
    {
     "title": "Certificate Expriration over time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$instance\"} - time()",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "TLS Version",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "probe_tls_version_info{instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ version }}"
      }
     ]
    },
    {
     "title": "Status Code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "probe_http_status_code", "legendFormat": "{{ instance }}" }
     ]
    },
    {
     "title": "HTTP Redirects (count)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "probe_http_redirects{instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  }
 ]
}